---
chdir: "/home/deploy/apps/quotesfromcollege/current"
environment: production
socket: tmp/sockets/thin.sock
timeout: 30
log: "log/thin.log"
pid: tmp/pids/thin.pid
max_conns: 1024
max_persistent_conns: 100
servers: 2
require: []
wait: 30
threadpool_size: 20
daemonize: true
tag: thin_server
onebyone: true
