default: &default
  plivo_id: <%= ENV['PLIVO_ID'] %>
  plivo_token: <%= ENV['PLIVO_TOKEN'] %>

development:
  <<: *default
  SECRET_KEY_BASE: <%= ENV['SECRET_KEY_BASE'] %>

production:
  <<: *default
