development:
  facebook_key: <%= ENV['FB_KEY'] %>
  facebook_secret: <%= ENV['FB_SECRET'] %>

  twitter_key: "YOUR_KEY"
  twitter_secret: "YOUR_SECRET"

  google_key: "YOUR_KEY"
  google_secret: "YOUR_SECRET"

production:
  facebook_key: <%= ENV['FB_KEY'] %>
  facebook_secret: <%= ENV['FB_SECRET'] %>

  twitter_key: "YOUR_KEY"
  twitter_secret: "YOUR_SECRET"

  google_key: "YOUR_KEY"
  google_secret: "YOUR_SECRET"
